export const predefinedEntries = [
    "Gierka w PESa",
    "Solenie w PESie",
    "Uninsall",
    "RageQuit",
    '"Gra dała tego gola"',
    "Ktoś lepiej gra po piwie",
    "Szymek nie umie odmieniać",
    '"Tego się nie da wygrać"',
    "Goticzek",
    "Prowokacja",
    "Bekanie",
    "Pierdzenie",
    '"User in your channel timed out"',
    '"Przejdźmy na discorda"',
    "Komsole vs PC",
    "Laptoki vs PC",
    "Apple jest najlepsze",
    "Boomerskie memy",
    "Zasypianie przy kompie",
    "Darcie się baby w tle",
    "Wspominanie zmarłych",
    "Soundboard",
    '"denerwuja mnie ceny gier"',
    "Pad się odłączył / rozładował",
    "Komiksy z nosaczem",
    '"Chcesz strimka na steamie?"',
    "Czilowanko",
];
